@echo off
mkdir "lib\app"
mkdir "lib\core\constants"
mkdir "lib\core\errors"
mkdir "lib\core\extensions"
mkdir "lib\core\theme"
mkdir "lib\core\utils"
mkdir "lib\core\widgets"
mkdir "lib\models"
mkdir "lib\services\firebase"
mkdir "lib\services\encryption"
mkdir "lib\providers"
mkdir "lib\features\auth\screens"
mkdir "lib\features\auth\widgets"
mkdir "lib\features\auth\controllers"
mkdir "lib\features\home\screens"
mkdir "lib\features\home\widgets"
mkdir "lib\features\chat\screens"
mkdir "lib\features\chat\widgets"
mkdir "lib\features\chat\controllers"
mkdir "lib\features\calls\screens"
mkdir "lib\features\calls\widgets"
mkdir "lib\features\calls\controllers"
mkdir "lib\features\status\screens"
mkdir "lib\features\status\widgets"
mkdir "lib\features\status\controllers"
mkdir "lib\features\contacts\screens"
mkdir "lib\features\contacts\controllers"
mkdir "lib\features\groups\screens"
mkdir "lib\features\groups\controllers"
mkdir "lib\features\profile\screens"
mkdir "lib\features\profile\controllers"
mkdir "lib\features\settings\screens"
mkdir "lib\features\settings\controllers"
mkdir "assets\images"
mkdir "assets\animations"
mkdir "assets\sounds"
mkdir "assets\fonts"

type nul > "lib\app\.gitkeep"
type nul > "lib\core\constants\.gitkeep"
type nul > "lib\core\errors\.gitkeep"
type nul > "lib\core\extensions\.gitkeep"
type nul > "lib\core\theme\.gitkeep"
type nul > "lib\core\utils\.gitkeep"
type nul > "lib\core\widgets\.gitkeep"
type nul > "lib\models\.gitkeep"
type nul > "lib\services\firebase\.gitkeep"
type nul > "lib\services\encryption\.gitkeep"
type nul > "lib\providers\.gitkeep"
type nul > "lib\features\auth\screens\.gitkeep"
type nul > "lib\features\auth\widgets\.gitkeep"
type nul > "lib\features\auth\controllers\.gitkeep"
type nul > "lib\features\home\screens\.gitkeep"
type nul > "lib\features\home\widgets\.gitkeep"
type nul > "lib\features\chat\screens\.gitkeep"
type nul > "lib\features\chat\widgets\.gitkeep"
type nul > "lib\features\chat\controllers\.gitkeep"
type nul > "lib\features\calls\screens\.gitkeep"
type nul > "lib\features\calls\widgets\.gitkeep"
type nul > "lib\features\calls\controllers\.gitkeep"
type nul > "lib\features\status\screens\.gitkeep"
type nul > "lib\features\status\widgets\.gitkeep"
type nul > "lib\features\status\controllers\.gitkeep"
type nul > "lib\features\contacts\screens\.gitkeep"
type nul > "lib\features\contacts\controllers\.gitkeep"
type nul > "lib\features\groups\screens\.gitkeep"
type nul > "lib\features\groups\controllers\.gitkeep"
type nul > "lib\features\profile\screens\.gitkeep"
type nul > "lib\features\profile\controllers\.gitkeep"
type nul > "lib\features\settings\screens\.gitkeep"
type nul > "lib\features\settings\controllers\.gitkeep"
type nul > "assets\images\.gitkeep"
type nul > "assets\animations\.gitkeep"
type nul > "assets\sounds\.gitkeep"
type nul > "assets\fonts\.gitkeep"

echo Done
