import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../models/chat_model.dart';
import '../../models/message_model.dart';
import '../../models/call_model.dart';
import '../../models/status_model.dart';
import '../../models/poll_model.dart';
import '../../models/scheduled_message_model.dart';

/// Database service powered by Supabase (PostgreSQL + Realtime)
///
/// Handles all CRUD and real-time operations for:
/// - Chats, Messages, Calls, Status, Polls, Scheduled messages
class DatabaseService {
  DatabaseService._();
  static final DatabaseService instance = DatabaseService._();

  SupabaseClient get _client => Supabase.instance.client;
  String? get _userId => _client.auth.currentUser?.id;

  // ─── CHATS ─────────────────────────────────────────────────

  /// Create a new chat
  Future<ChatModel> createChat(ChatModel chat) async {
    final data = await _client.from('chats').insert(chat.toJson()).select().single();
    return ChatModel.fromJson(data);
  }

  /// Get a single chat by ID
  Future<ChatModel?> getChat(String chatId) async {
    final data = await _client
        .from('chats')
        .select()
        .eq('id', chatId)
        .maybeSingle();
    if (data == null) return null;
    return ChatModel.fromJson(data);
  }

  /// Get all chats for the current user (where user is a participant)
  Future<List<ChatModel>> getUserChats() async {
    if (_userId == null) return [];
    final data = await _client
        .from('chats')
        .select()
        .contains('participants', [_userId!])
        .order('last_activity', ascending: false);
    return data.map((json) => ChatModel.fromJson(json)).toList();
  }

  /// Stream all chats for the current user (real-time)
  Stream<List<ChatModel>> streamUserChats() {
    if (_userId == null) return Stream.value([]);
    return _client
        .from('chats')
        .stream(primaryKey: ['id'])
        .map((data) {
          return data
              .where((chat) {
                final participants = List<String>.from(chat['participants'] ?? []);
                return participants.contains(_userId);
              })
              .map((json) => ChatModel.fromJson(json))
              .toList()
            ..sort((a, b) {
              final aTime = a.lastActivity ?? a.createdAt ?? DateTime(2000);
              final bTime = b.lastActivity ?? b.createdAt ?? DateTime(2000);
              return bTime.compareTo(aTime);
            });
        });
  }

  /// Update chat fields
  Future<void> updateChat(String chatId, Map<String, dynamic> updates) async {
    await _client.from('chats').update(updates).eq('id', chatId);
  }

  /// Find or create a private chat between two users
  Future<ChatModel> getOrCreatePrivateChat(String otherUserId) async {
    if (_userId == null) throw Exception('Not authenticated');

    // Check if a private chat already exists between these two users
    final existing = await _client
        .from('chats')
        .select()
        .eq('type', 'private')
        .contains('participants', [_userId!])
        .contains('participants', [otherUserId])
        .maybeSingle();

    if (existing != null) return ChatModel.fromJson(existing);

    // Create new private chat
    final newChat = ChatModel(
      chatId: '', // Generated by Supabase
      type: ChatType.private_,
      participants: [_userId!, otherUserId],
      createdBy: _userId!,
      createdAt: DateTime.now(),
      lastActivity: DateTime.now(),
    );

    return createChat(newChat);
  }

  /// Delete a chat (soft-delete for the user, or group deletion)
  Future<void> deleteChat(String chatId) async {
    await _client.from('chats').delete().eq('id', chatId);
  }

  // ─── MESSAGES ──────────────────────────────────────────────

  /// Send a message
  Future<MessageModel> sendMessage(MessageModel message) async {
    final data = await _client
        .from('messages')
        .insert(message.toJson())
        .select()
        .single();

    // Update the chat's last_message and last_activity
    await _client.from('chats').update({
      'last_message': {
        'text': message.encryptedText.length > 50
            ? '${message.encryptedText.substring(0, 50)}...'
            : message.encryptedText,
        'sender_id': message.senderId,
        'timestamp': message.timestamp.toIso8601String(),
        'type': message.type.name,
      },
      'last_activity': DateTime.now().toIso8601String(),
    }).eq('id', message.chatId);

    return MessageModel.fromJson(data);
  }

  /// Get messages for a chat (paginated)
  Future<List<MessageModel>> getMessages(
    String chatId, {
    int limit = 50,
    int offset = 0,
  }) async {
    final data = await _client
        .from('messages')
        .select()
        .eq('chat_id', chatId)
        .order('timestamp', ascending: false)
        .range(offset, offset + limit - 1);
    return data.map((json) => MessageModel.fromJson(json)).toList();
  }

  /// Stream messages for a chat (real-time)
  Stream<List<MessageModel>> streamMessages(String chatId) {
    return _client
        .from('messages')
        .stream(primaryKey: ['id'])
        .eq('chat_id', chatId)
        .order('timestamp')
        .map((data) => data.map((json) => MessageModel.fromJson(json)).toList());
  }

  /// Update message fields (reactions, read status, edit, delete)
  Future<void> updateMessage(String messageId, Map<String, dynamic> updates) async {
    await _client.from('messages').update(updates).eq('message_id', messageId);
  }

  /// Mark messages as read
  Future<void> markMessagesAsRead(String chatId) async {
    if (_userId == null) return;
    // Update all unread messages in the chat from other users
    await _client.rpc('mark_messages_read', params: {
      'p_chat_id': chatId,
      'p_user_id': _userId!,
    });
  }

  /// Delete message (soft delete)
  Future<void> deleteMessage(String messageId, {bool forEveryone = false}) async {
    final updates = <String, dynamic>{
      'is_deleted': true,
      'deleted_at': DateTime.now().toIso8601String(),
    };
    if (forEveryone) updates['deleted_for_everyone'] = true;
    await _client.from('messages').update(updates).eq('message_id', messageId);
  }

  // ─── CALLS ─────────────────────────────────────────────────

  /// Create a call record
  Future<CallModel> createCall(CallModel call) async {
    final data = await _client.from('calls').insert(call.toJson()).select().single();
    return CallModel.fromJson(data);
  }

  /// Get call history for the current user
  Future<List<CallModel>> getCallHistory({int limit = 50}) async {
    if (_userId == null) return [];
    final data = await _client
        .from('calls')
        .select()
        .or('caller_id.eq.$_userId,receiver_ids.cs.{$_userId}')
        .order('started_at', ascending: false)
        .limit(limit);
    return data.map((json) => CallModel.fromJson(json)).toList();
  }

  /// Stream active call for current user (real-time signaling)
  Stream<List<CallModel>> streamActiveCalls() {
    if (_userId == null) return Stream.value([]);
    return _client
        .from('calls')
        .stream(primaryKey: ['id'])
        .inFilter('status', ['ringing', 'accepted'])
        .map((data) => data
            .map((json) => CallModel.fromJson(json))
            .where((call) =>
                call.callerId == _userId ||
                call.receiverIds.contains(_userId))
            .toList());
  }

  /// Update call (accept, reject, end, signaling data)
  Future<void> updateCall(String callId, Map<String, dynamic> updates) async {
    await _client.from('calls').update(updates).eq('id', callId);
  }

  // ─── STATUS / STORIES ─────────────────────────────────────

  /// Create a status update
  Future<StatusModel> createStatus(StatusModel status) async {
    final data = await _client.from('status').insert(status.toJson()).select().single();
    return StatusModel.fromJson(data);
  }

  /// Get active statuses (not expired) from contacts
  Future<List<StatusModel>> getActiveStatuses(List<String> contactUserIds) async {
    if (contactUserIds.isEmpty) return [];
    final now = DateTime.now().toIso8601String();
    final data = await _client
        .from('status')
        .select()
        .inFilter('user_id', contactUserIds)
        .gt('expires_at', now)
        .order('created_at', ascending: false);
    return data.map((json) => StatusModel.fromJson(json)).toList();
  }

  /// Get my statuses
  Future<List<StatusModel>> getMyStatuses() async {
    if (_userId == null) return [];
    final data = await _client
        .from('status')
        .select()
        .eq('user_id', _userId!)
        .order('created_at', ascending: false);
    return data.map((json) => StatusModel.fromJson(json)).toList();
  }

  /// Mark status as seen
  Future<void> markStatusSeen(String statusId) async {
    if (_userId == null) return;
    await _client.rpc('mark_status_seen', params: {
      'p_status_id': statusId,
      'p_user_id': _userId!,
    });
  }

  // ─── POLLS ─────────────────────────────────────────────────

  /// Create a poll
  Future<PollModel> createPoll(PollModel poll) async {
    final data = await _client.from('polls').insert(poll.toJson()).select().single();
    return PollModel.fromJson(data);
  }

  /// Get poll by ID
  Future<PollModel?> getPoll(String pollId) async {
    final data = await _client
        .from('polls')
        .select()
        .eq('id', pollId)
        .maybeSingle();
    if (data == null) return null;
    return PollModel.fromJson(data);
  }

  /// Vote on a poll
  Future<void> votePoll(String pollId, String optionId) async {
    if (_userId == null) return;
    await _client.rpc('vote_poll', params: {
      'p_poll_id': pollId,
      'p_option_id': optionId,
      'p_user_id': _userId!,
    });
  }

  // ─── SCHEDULED MESSAGES ────────────────────────────────────

  /// Schedule a message
  Future<ScheduledMessageModel> scheduleMessage(ScheduledMessageModel msg) async {
    final data = await _client
        .from('scheduled_messages')
        .insert(msg.toJson())
        .select()
        .single();
    return ScheduledMessageModel.fromJson(data);
  }

  /// Get scheduled messages for current user
  Future<List<ScheduledMessageModel>> getScheduledMessages() async {
    if (_userId == null) return [];
    final data = await _client
        .from('scheduled_messages')
        .select()
        .eq('sender_id', _userId!)
        .eq('status', 'pending')
        .order('scheduled_at');
    return data.map((json) => ScheduledMessageModel.fromJson(json)).toList();
  }

  /// Cancel a scheduled message
  Future<void> cancelScheduledMessage(String id) async {
    await _client
        .from('scheduled_messages')
        .update({'status': 'cancelled'})
        .eq('id', id);
  }

  // ─── PRESENCE (Supabase Realtime) ──────────────────────────

  /// Subscribe to typing indicators for a chat
  RealtimeChannel subscribeToTyping(
    String chatId,
    void Function(Map<String, dynamic> payload) onTyping,
  ) {
    final channel = _client.channel('typing:$chatId');
    channel.onBroadcast(
      event: 'typing',
      callback: (payload) => onTyping(payload),
    ).subscribe();
    return channel;
  }

  /// Send typing indicator
  Future<void> sendTypingIndicator(String chatId, bool isTyping) async {
    final channel = _client.channel('typing:$chatId');
    await channel.sendBroadcastMessage(
      event: 'typing',
      payload: {
        'user_id': _userId,
        'is_typing': isTyping,
        'timestamp': DateTime.now().toIso8601String(),
      },
    );
  }

  // ─── GROUPS ────────────────────────────────────────────────

  /// Create a new group chat
  Future<ChatModel> createGroup({
    required String groupName,
    required String description,
    required List<String> memberIds,
    String? avatarUrl,
  }) async {
    if (_userId == null) throw Exception('Not authenticated');
    
    final newGroup = ChatModel(
      chatId: '', // Generated by Supabase
      type: ChatType.group,
      participants: [_userId!, ...memberIds],
      admins: [_userId!],
      createdBy: _userId!,
      name: groupName,
      description: description,
      avatarUrl: avatarUrl,
      createdAt: DateTime.now(),
      lastActivity: DateTime.now(),
    );

    final data = await _client
        .from('chats')
        .insert(newGroup.toJson())
        .select()
        .single();
    return ChatModel.fromJson(data);
  }

  /// Get a group chat by ID
  Future<ChatModel?> getGroup(String groupId) async {
    final data = await _client
        .from('chats')
        .select()
        .eq('id', groupId)
        .maybeSingle();
    if (data == null) return null;
    return ChatModel.fromJson(data);
  }

  /// Add members to a group
  Future<void> addGroupMembers(String groupId, List<String> memberIds) async {
    if (_userId == null) return;
    
    // Get current group
    final group = await getGroup(groupId);
    if (group == null) return;
    
    // Add new members (avoid duplicates)
    final updatedParticipants = {...group.participants, ...memberIds}.toList();
    
    await _client.from('chats').update({
      'participants': updatedParticipants,
    }).eq('id', groupId);
  }

  /// Remove a member from a group
  Future<void> removeGroupMember(String groupId, String memberId) async {
    if (_userId == null) return;
    
    // Get current group
    final group = await getGroup(groupId);
    if (group == null) return;
    
    // Remove member
    final updatedParticipants = group.participants
        .where((id) => id != memberId)
        .toList();
    
    // Also remove from admins if applicable
    final updatedAdmins = group.admins
        .where((id) => id != memberId)
        .toList();
    
    await _client.from('chats').update({
      'participants': updatedParticipants,
      'admins': updatedAdmins,
    }).eq('id', groupId);
  }

  /// Make a user a group admin
  Future<void> promoteToAdmin(String groupId, String userId) async {
    if (_userId == null) return;
    
    final group = await getGroup(groupId);
    if (group == null) return;
    
    // Check if current user is admin
    if (!group.admins.contains(_userId!)) {
      throw Exception('Only admins can promote members');
    }
    
    // Add to admins if not already
    final updatedAdmins = [...group.admins];
    if (!updatedAdmins.contains(userId)) {
      updatedAdmins.add(userId);
    }
    
    await _client.from('chats').update({
      'admins': updatedAdmins,
    }).eq('id', groupId);
  }

  /// Remove admin status from a user
  Future<void> demoteFromAdmin(String groupId, String userId) async {
    if (_userId == null) return;
    
    final group = await getGroup(groupId);
    if (group == null) return;
    
    // Check if current user is admin
    if (!group.admins.contains(_userId!)) {
      throw Exception('Only admins can demote members');
    }
    
    // Remove from admins
    final updatedAdmins = group.admins
        .where((id) => id != userId)
        .toList();
    
    await _client.from('chats').update({
      'admins': updatedAdmins,
    }).eq('id', groupId);
  }

  /// Update group info (name, description, avatar)
  Future<void> updateGroupInfo(
    String groupId, {
    String? name,
    String? description,
    String? avatarUrl,
  }) async {
    if (_userId == null) return;
    
    final updates = <String, dynamic>{};
    if (name != null) updates['name'] = name;
    if (description != null) updates['description'] = description;
    if (avatarUrl != null) updates['avatar_url'] = avatarUrl;
    
    if (updates.isNotEmpty) {
      await _client.from('chats').update(updates).eq('id', groupId);
    }
  }

  /// Leave a group
  Future<void> leaveGroup(String groupId) async {
    if (_userId == null) return;
    
    final group = await getGroup(groupId);
    if (group == null) return;
    
    // Remove current user from participants
    final updatedParticipants = group.participants
        .where((id) => id != _userId!)
        .toList();
    
    // Also remove from admins if applicable
    final updatedAdmins = group.admins
        .where((id) => id != _userId!)
        .toList();
    
    // If no admins left and there are still participants, promote the first one
    if (updatedAdmins.isEmpty && updatedParticipants.isNotEmpty) {
      updatedAdmins.add(updatedParticipants.first);
    }
    
    await _client.from('chats').update({
      'participants': updatedParticipants,
      'admins': updatedAdmins,
    }).eq('id', groupId);
  }

  /// Delete a group (only by admin)
  Future<void> deleteGroup(String groupId) async {
    if (_userId == null) return;
    
    final group = await getGroup(groupId);
    if (group == null) return;
    
    // Check if current user is admin
    if (!group.admins.contains(_userId!)) {
      throw Exception('Only admins can delete a group');
    }
    
    await _client.from('chats').delete().eq('id', groupId);
  }

  /// Get members info for a group (user details)
  Future<List<Map<String, dynamic>>> getGroupMembers(String groupId) async {
    final group = await getGroup(groupId);
    if (group == null) return [];
    
    if (group.participants.isEmpty) return [];
    
    final members = await _client
        .from('users')
        .select()
        .inFilter('user_id', group.participants);
    
    return members as List<Map<String, dynamic>>;
  }

  /// Stream group chat (real-time updates to group info)
  Stream<ChatModel?> streamGroup(String groupId) {
    return _client
        .from('chats')
        .stream(primaryKey: ['id'])
        .eq('id', groupId)
        .map((data) {
          if (data.isEmpty) return null;
          return ChatModel.fromJson(data.first);
        });
  }
}
